package ua.com.lab.guestbook.db;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class DatabaseService {

    // URL згідно з завданням
    private static final String H2_URL = "jdbc:h2:file:./data/guest;AUTO_SERVER=TRUE";
    private static final String H2_USER = "sa"; // default
    private static final String H2_PASS = ""; // default

    // Singleton pattern
    private static DatabaseService instance;

    private DatabaseService() {
        // Завантажуємо H2 драйвер
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException("H2 Driver not found!", e);
        }
    }

    public static synchronized DatabaseService getInstance() {
        if (instance == null) {
            instance = new DatabaseService();
        }
        return instance;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(H2_URL, H2_USER, H2_PASS);
    }

    // Метод для ініціалізації. Створює таблицю.
    public void initializeDatabase() {
        String createTableSql = """
            CREATE TABLE IF NOT EXISTS comments (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                author VARCHAR(64) NOT NULL,
                text VARCHAR(1000) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
            )
            """;

        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(createTableSql);
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database", e);
        }
    }

    // Отримуємо всі коментарі (новіші зверху)
    public List<Comment> getComments() throws SQLException {
        List<Comment> comments = new ArrayList<>();
        String sql = "SELECT id, author, text, created_at FROM comments ORDER BY created_at DESC";

        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                comments.add(new Comment(
                        rs.getLong("id"),
                        rs.getString("author"),
                        rs.getString("text"),
                        rs.getTimestamp("created_at").toInstant()
                ));
            }
        }
        return comments;
    }

    // Додаємо коментар і повертаємо його з ID
    public Comment addComment(String author, String text) throws SQLException {
        String sql = "INSERT INTO comments (author, text) VALUES (?, ?)";

        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            pstmt.setString(1, author);
            pstmt.setString(2, text);
            pstmt.executeUpdate();

            try (ResultSet generatedKeys = pstmt.getGeneratedKeys()) {
                if (generatedKeys.next()) {
                    long id = generatedKeys.getLong(1);
                    // Повертаємо щойно створений коментар (потрібно знову запитати)
                    return getCommentById(id);
                } else {
                    throw new SQLException("Creating comment failed, no ID obtained.");
                }
            }
        }
    }

    // Допоміжний метод, щоб отримати коментар по ID (для логування)
    private Comment getCommentById(long id) throws SQLException {
        String sql = "SELECT id, author, text, created_at FROM comments WHERE id = ?";
        try (Connection conn = getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setLong(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return new Comment(
                            rs.getLong("id"),
                            rs.getString("author"),
                            rs.getString("text"),
                            rs.getTimestamp("created_at").toInstant()
                    );
                }
            }
        }
        return null; // or throw exception
    }
}